# Numpy
* NumPy(Numerical Python) is a fundamental library for Python numerical computing. It provides efficient multi-dimensional array objects and various mathematical functions for handling large datasets making it a critical tool for professionals in fields that require heavy computation.

In [23]:
import numpy as np

In [24]:
num = np.array([1,2,3,4,5])
print(num)

[1 2 3 4 5]


In [25]:
type(num)

numpy.ndarray

In [26]:
num = np.array([1,2,3,4,5], dtype = float)
print(num)

[1. 2. 3. 4. 5.]


In [27]:
nums = np.array([[10,20,30,40], [50,60,70,80], [90,100,110,120]])
print(nums)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [28]:
len(nums)

3

In [29]:
nums.ndim

2

In [30]:
nums.shape

(3, 4)

In [31]:
nums.dtype

dtype('int64')

In [32]:
nums[0:3, 1:4]

array([[ 20,  30,  40],
       [ 60,  70,  80],
       [100, 110, 120]])

In [33]:
nums[0,0:1] = 0
nums

array([[  0,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [39]:
np.zeros((5,5), dtype='int' )

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [40]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
np.full((5,4),25, dtype='int32')

array([[25, 25, 25, 25],
       [25, 25, 25, 25],
       [25, 25, 25, 25],
       [25, 25, 25, 25],
       [25, 25, 25, 25]], dtype=int32)

In [64]:
np.random.randint(22, 90, size=(6,6))

array([[29, 39, 45, 89, 62, 84],
       [27, 84, 80, 50, 42, 89],
       [61, 81, 42, 62, 35, 49],
       [46, 74, 59, 58, 67, 79],
       [33, 25, 22, 58, 26, 47],
       [89, 60, 36, 79, 73, 52]], dtype=int32)

In [65]:
np.random.rand(8,9)

array([[7.05997120e-01, 7.63914165e-01, 8.42649873e-01, 8.75990365e-01,
        2.47945415e-02, 7.59590568e-02, 5.65730246e-01, 6.76118281e-01,
        8.27369394e-01],
       [3.50553834e-02, 9.17478780e-01, 1.00980360e-01, 3.71606201e-01,
        3.84974271e-01, 7.05391481e-01, 1.09161467e-01, 4.98465274e-01,
        6.45655790e-01],
       [9.70635482e-01, 2.72353092e-01, 8.95055658e-01, 7.81821228e-01,
        7.03198242e-01, 7.75937302e-01, 6.24892340e-01, 3.99741302e-01,
        2.09340629e-01],
       [4.12002119e-01, 2.67965469e-01, 9.22497277e-01, 1.02484876e-01,
        9.51848075e-01, 4.99933046e-01, 6.50051682e-01, 5.40270674e-01,
        8.01592840e-01],
       [5.62794700e-01, 8.88711156e-01, 9.81571922e-01, 4.12337310e-01,
        9.53010217e-01, 7.40894646e-02, 8.23757843e-01, 6.17133489e-01,
        4.37352995e-01],
       [7.29022156e-01, 7.82745899e-01, 4.49964274e-04, 2.01692826e-01,
        3.93283452e-01, 6.48562318e-01, 6.29629266e-01, 2.65132725e-01,
        1.6

In [66]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [83]:
# Extract all the first 3 rows of the last 5 columns in a given numpy 2D array
nums_2d_array = np.array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])
nums_2d_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [88]:
nums_2d_array[0:4, 1:6]

array([[ 2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12],
       [14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24]])

In [89]:
nums_2d_array[0:3]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [99]:
zeroes = np.zeros((5,5), dtype='int')
print(zeroes)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [100]:
zeroes[5//2,:] = 1
zeroes[:, 5//2] = 1
print(zeroes)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [103]:
nums = np.array([1,2,3,4,5,6,7,8])
nums + 10

array([11, 12, 13, 14, 15, 16, 17, 18])