# Numpy Array Creation

In [1]:
import numpy as np

In [2]:
marks = np.array([65, 69, 84, 86, 99]) #1D Array
marks

array([65, 69, 84, 86, 99])

In [3]:
num = np.array([[10,20,30],[40,50,60],[70,80,90]]) #2D Array
num

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [4]:
zeroes_1d_array = np.zeros(5) #1D zeroes array
zeroes_1d_array

array([0., 0., 0., 0., 0.])

In [5]:
zeroes_2d_array = np.zeros((5, 5)) #2D zeroes array
zeroes_2d_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
ones_1d_array = np.ones(5) #1D ones array
ones_1d_array

array([1., 1., 1., 1., 1.])

In [7]:
ones_2d_array = np.ones((5, 5)) #2D ones array
ones_2d_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
targeted_value_array = np.full((5), 9) #1D targeted value array
targeted_value_array

array([9, 9, 9, 9, 9])

In [9]:
targeted_value_array = np.full((5, 5), 9) #2D targeted value array
targeted_value_array

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [10]:
number_in_range = np.arange(1, 21, 1) # np.arange(start,stop,step) generates numbers in range
number_in_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
identity_matrix = np.eye(5) #Square matrix, ones on diagonal, & zeros elsewhere.
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Numpy array properties & operations

In [12]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90], [100,110,120]]) #2D Array
arr

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [13]:
arr.shape # 4 rows and 3 columns

(4, 3)

In [14]:
arr.size #returns size of array

12

In [15]:
one_dimension_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120]) #1D Array
two_dimension_array = np.array([[10,20,30],[40,50,60],[70,80,90], [100,110,120]]) #2D Array
three_dimension_array = np.array([[[10,20,30],[40,50,60],[70,80,90], [100,110,120]]]) #3D Array
print(one_dimension_array.ndim) #returns dimension of array
print(two_dimension_array.ndim)
print(three_dimension_array.ndim)

1
2
3


In [16]:
type(one_dimension_array)

numpy.ndarray

In [17]:
nums = np.array([65, 69, 84, 86, 99.2])
nums.dtype # float64 indicates array has float value

dtype('float64')

In [18]:
nums = np.array([65.2, 69.8, 84.6, 86.2, 99.2])
arr = nums.astype(int) #changes type of value
arr.dtype

dtype('int64')

# Operations in numpy

In [19]:
number = np.array([1,2,3,4,5])
number + 2

array([3, 4, 5, 6, 7])

In [20]:
number ** 2

array([ 1,  4,  9, 16, 25])

In [21]:
number - 2

array([-1,  0,  1,  2,  3])

# Aggregation functions in python

In [22]:
nums = np.array([10,20,30,40,50])
np.sum(nums)

np.int64(150)

In [23]:
np.mean(nums)

np.float64(30.0)

In [24]:
np.min(nums)

np.int64(10)

In [25]:
np.max(nums)

np.int64(50)

In [26]:
np.std(nums)

np.float64(14.142135623730951)

In [27]:
np.var(nums)

np.float64(200.0)

# Indexing and slicing in numpy

In [28]:
nums = np.array([22,23,24,25,26,27,28,29,30]) 
nums

array([22, 23, 24, 25, 26, 27, 28, 29, 30])

In [29]:
nums[2]

np.int64(24)

In [30]:
matrix = np.array([[19,20,21],[22,23,24],[25,26,27],[28,29,30], [31,32,33]])
matrix

array([[19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [31]:
matrix[1,1]

np.int64(23)

In [32]:
matrix[1:2,0:2] #[start, stop, step]

array([[22, 23]])

In [33]:
matrix[matrix > 21] #returns elements greater than 21

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [34]:
matrix.shape

(5, 3)

In [35]:
matrix.reshape(3,5) #changes view only and does not create copy

array([[19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33]])

In [36]:
matrix.ravel() #convert 2D arrray into 1D array and returns view

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [37]:
matrix.flatten() #convert 2D arrray into 1D array and returns copy

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

# Manipulating Numpy Arrays

In [38]:
arr = np.array([1,2,3,4,5])

In [39]:
insert_in_array = np.insert(arr, 5, 6)
insert_in_array

array([1, 2, 3, 4, 5, 6])

In [40]:
insert_in_array = np.insert(arr, 0, 0)
insert_in_array

array([0, 1, 2, 3, 4, 5])

In [41]:
matrix = np.array([[19,20,21],[22,23,24],[25,26,27],[28,29,30], [31,32,33]])
matrix

array([[19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [42]:
insert_in_matrix = np.insert(matrix,1, [0,0,0], axis=0)
insert_in_matrix

array([[19, 20, 21],
       [ 0,  0,  0],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [43]:
append_in_matrix = np.append(matrix,[34,35,36])
append_in_matrix

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36])

In [44]:
num1 = ([1,2,3,4,5])
num2 = ([6,7,8,9,10])
concatenate_in_matrix = np.concatenate((num1, num2), axis = 0 )
concatenate_in_matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr = np.array([1,2,3,4,5])
remove_in_array = np.delete(arr, 2)
remove_in_array 

array([1, 2, 4, 5])

In [46]:
matrix = np.array([[19,20,21],[22,23,24],[25,26,27],[28,29,30], [31,32,33]])
matrix

array([[19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [47]:
removed_element = np.delete(matrix, 0, axis=0)
removed_element

array([[22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [48]:
num1 = ([1,2,3,4,5])
num2 = ([6,7,8,9,10])
num3 = ([11,12,13,14,15])
num4 = ([16,17,18,19,20])
horizontical_stacking_in_matrix = np.hstack((num1, num2, num3, num4)) #stacking horizontically
horizontical_stacking_in_matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
num1 = ([1,2,3,4,5])
num2 = ([6,7,8,9,10])
num3 = ([11,12,13,14,15])
num4 = ([16,17,18,19,20])
vertical_stacking_in_matrix = np.vstack((num1, num2, num3, num4)) #stacking vertically
vertical_stacking_in_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [50]:
arr = np.array([10,20,30,40,50,60,70,80,90])
splitted_array = np.split(arr, 3)
splitted_array

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]

# Broadcasting and vectorisation

In [51]:
prices = np.array([100,200,300,400,500])
discount = 10
final_price = prices - (prices * discount / 100)
final_price

array([ 90., 180., 270., 360., 450.])

In [52]:
arr = np.array([100,200,300,400,500])
result = arr + 10
result

array([110, 210, 310, 410, 510])

In [53]:
matrix = np.array([[19,20,21],[22,23,24],[25,26,27],[28,29,30], [31,32,33]])
vector = np.array([10,20,30])
result = matrix + vector
result

array([[29, 40, 51],
       [32, 43, 54],
       [35, 46, 57],
       [38, 49, 60],
       [41, 52, 63]])

In [54]:
num1 = np.array([1,2,3,4,5])
num2 = np.array([6,7,8,9,10])
num3 = np.array([11,12,13,14,15])
num4 = np.array([16,17,18,19,20])
Sum = num1 + num2 + num3 + num4
Sum

array([34, 38, 42, 46, 50])

# Handling missing values

In [55]:
arr = np.array([10,20,np.nan,40,np.nan,60]) #check missing value
print(np.isnan(arr))

[False False  True False  True False]


In [56]:
arr = np.array([10,20,np.nan,40,np.nan,60]) #replace missing value
updated_array = np.nan_to_num(arr, nan=30)
updated_array

array([10., 20., 30., 40., 30., 60.])

In [57]:
arr = np.array([10,20,np.inf,40,-np.inf,60]) #check infinity value
print(np.isinf(arr))

[False False  True False  True False]


In [58]:
arr = np.array([10,20,np.inf,40,-np.inf,60]) #replace infinity value
updated_array = np.nan_to_num(arr, posinf=1, neginf=0)
updated_array

array([10., 20.,  1., 40.,  0., 60.])